from django.db import models

# Create your models here.
class values:
    CO:float
    PRD:float
    CTF:float
    WFA:float
    GSBC:float
    RO:float
    AO:float
    Flowrate:float
    Hours:float
    CTS_Losses:float
    TheCTS_Losses:float
    WW:float
    TheWW:float
    UEXLOS:float
    TheUEXLOS:float
    P1_FlowPercent:float
    P2_Var1:float
    P2_Var1:float
    P3_Var1:float
    P4_Var1:float
    P5_Var1:float
    P6_Var1:float
    P7_Var1:float
    P1_Var2:float
    P2_Var2:float
    P3_Var2:float
    P4_Var2:float
    P5_Var2:float
    P6_Var2:float
    P7_Var2:float
    P1_Var3:float
    P2_Var3:float
    P3_Var3:float
    P4_Var3:float
    P5_Var3:float
    P6_Var3:float
    P7_Var3:float
    P1_Impurities:float
    P2_Impurities:float
    P3_Impurities:float
    P4_Impurities:float
    P5_Impurities:float
    P6_Impurities:float
    P1_Impurities:float
    P1_Mass:float
    P2_Mass:float
    P3_Mass:float
    P4_Mass:float
    P5_Mass:float
    P6_Mass:float
    P1_Wax1:float
    P2_Wax1:float
    P3_Wax1:float
    P4_Wax1:float
    P5_Wax1:float
    P6_Wax1:float
    P1_Ass1:float
    P2_Ass1:float
    P3_Ass1:float
    P4_Ass1:float
    P5_Ass1:float
    P6_Ass1:float
    P1_TheAss1:float
    P2_TheAss1:float
    P3_TheAss1:float
    P4_TheAss1:float
    P5_TheAss1:float
    P6_TheAss1:float
    P1_Ass2:float
    P2_Ass2:float
    P3_Ass2:float
    P4_Ass2:float
    P5_Ass2:float
    P6_Ass2:float
    P1_TheAss2:float
    P2_TheAss2:float
    P3_TheAss2:float
    P4_TheAss2:float
    P5_TheAss2:float
    P6_TheAss2:float
    P1_Ass3:float
    P2_Ass3:float
    P3_Ass3:float
    P4_Ass3:float
    P5_Ass3:float
    P6_Ass3:float
    P1_TheAss3:float
    P2_TheAss3:float
    P3_TheAss3:float
    P4_TheAss3:float
    P5_TheAss3:float
    P6_TheAss3:float
    P1_Ass4:float
    P2_Ass4:float
    P3_Ass4:float
    P4_Ass4:float
    P5_Ass4:float
    P6_Ass4:float
    P1_TheAss4:float
    P2_TheAss4:float
    P3_TheAss4:float
    P4_TheAss4:float
    P5_TheAss4:float
    P6_TheAss4:float
    P2_Iter:float
    P3_Iter:float
    P4_Iter:float
    P5_Iter:float
    P6_Iter:float
    P1_FlowPercent:float
    P2_FlowPercent:float
    P3_FlowPercent:float
    P4_FlowPercent:float
    P5_FlowPercent:float
    P6_FlowPercent:float
    P1_calc1:float
    P2_calc1:float
    P3_calc1:float
    P4_calc1:float
    P5_calc1:float
    P6_calc1:float
    P1_calc1withfactor:float
    P2_calc1withfactor:float
    P3_calc1withfactor:float
    P4_calc1withfactor:float
    P5_calc1withfactor:float
    P6_calc1withfactor:float
    P1_Loss1:float
    P2_Loss1:float
    P3_Loss1:float
    P4_Loss1:float
    P5_Loss1:float
    P6_Loss1:float
    P1_Loss1withfactor:float
    P2_Loss1withfactor:float
    P3_Loss1withfactor:float
    P4_Loss1withfactor:float
    P5_Loss1withfactor:float
    P6_Loss1withfactor:float
    P1_calc2:float
    P2_calc2:float
    P3_calc2:float
    P4_calc2:float
    P5_calc2:float
    P6_calc2:float
    P1_calc3:float
    P2_calc3:float
    P3_calc3:float
    P4_calc3:float
    P5_calc3:float
    P6_calc3:float
    P1_calc4:float
    P2_calc4:float
    P3_calc4:float
    P4_calc4:float
    P5_calc4:float
    P6_calc4:float
    P1_calc5:float
    P2_calc5:float
    P3_calc5:float
    P4_calc5:float
    P5_calc5:float
    P6_calc5:float
    TUCMASS:float
    FLOWLOSS:float
    YIELD:float
    TUCFACT:float
    FS:float
    P2_TheIter:float
    P3_TheIter:float
    P4_TheIter:float
    P5_TheIter:float
    P6_TheIter:float
    P2_TheFlowPercent:float
    P3_TheFlowPercent:float
    P4_TheFlowPercent:float
    P5_TheFlowPercent:float
    P6_TheFlowPercent:float
    P1_Thecalc1:float
    P2_Thecalc1:float
    P3_Thecalc1:float
    P4_Thecalc1:float
    P5_Thecalc1:float
    P6_Thecalc1:float
    P1_Thecalc1withfactor:float
    P2_Thecalc1withfactor:float
    P3_Thecalc1withfactor:float
    P4_Thecalc1withfactor:float
    P5_Thecalc1withfactor:float
    P6_Thecalc1withfactor:float
    P1_TheLoss1:float
    P2_TheLoss1:float
    P3_TheLoss1:float
    P4_TheLoss1:float
    P5_TheLoss1:float
    P6_TheLoss1:float
    P1_TheLoss1withfactor:float
    P2_TheLoss1withfactor:float
    P3_TheLoss1withfactor:float
    P4_TheLoss1withfactor:float
    P5_TheLoss1withfactor:float
    P6_TheLoss1withfactor:float
    P1_Thecalc2:float
    P2_Thecalc2:float
    P3_Thecalc2:float
    P4_Thecalc2:float
    P5_Thecalc2:float
    P6_Thecalc2:float
    P1_Thecalc3:float
    P2_Thecalc3:float
    P3_Thecalc3:float
    P4_Thecalc3:float
    P5_Thecalc3:float
    P6_Thecalc3:float
    P1_Thecalc4:float
    P2_Thecalc4:float
    P3_Thecalc4:float
    P4_Thecalc4:float
    P5_Thecalc4:float
    P6_Thecalc4:float
    P1_Thecalc5:float
    P2_Thecalc5:float
    P3_Thecalc5:float
    P4_Thecalc5:float
    P5_Thecalc5:float
    P6_Thecalc5:float
    TheTUCMASS:float
    TheFLOWLOSS:float
    TheYIELD:float
    TheTUCFACT:float
    TheFS:float
    A_OInput:float
    A_OLCT:float
    B_OLCT:float
    C_OLCT:float
    D_OLCT:float
    A_SDGG:float
    B_SDGG:float
    C_SDGG:float
    D_SDGG:float
    A_AO:float
    B_AO:float
    C_AO:float
    D_AO:float
    A_OIC:float
    B_OIC:float
    C_OIC:float
    D_OIC:float
    A_OIWFA:float
    B_OIWFA:float
    C_OIWFA:float
    D_OIWFA:float
    A_PMI:float
    B_PMI:float
    C_PMI:float
    D_PMI:float
    A_D:float
    B_D:float
    C_D:float
    D_D:float
    A_WW:float
    B_WW:float
    C_WW:float
    D_WW:float
    A_UEXLOS:float
    B_UEXLOS:float
    C_UEXLOS:float
    D_UEXLOS:float
    A_FLOWOP:float
    B_FLOWOP:float
    C_FLOWOP:float
    D_FLOWOP:float
    A_TOTAL:float
    B_TOTAL:float
    C_TOTAL:float
    D_TOTAL:float
    A_TheOInput:float
    A_TheOLCT:float
    B_TheOLCT:float
    C_TheOLCT:float
    D_TheOLCT:float
    A_TheSDGG:float
    B_TheSDGG:float
    C_TheSDGG:float
    D_TheSDGG:float
    A_TheAO:float
    B_TheAO:float
    C_TheAO:float
    D_TheAO:float
    A_TheOIC:float
    B_TheOIC:float
    C_TheOIC:float
    D_TheOIC:float
    A_TheOIWFA:float
    B_TheOIWFA:float
    C_TheOIWFA:float
    D_TheOIWFA:float
    A_ThePMI:float
    B_ThePMI:float
    C_ThePMI:float
    D_ThePMI:float
    A_TheD:float
    B_TheD:float
    C_TheD:float
    D_TheD:float
    A_TheWW:float
    B_TheWW:float
    C_TheWW:float
    D_TheWW:float
    A_TheUEXLOS:float
    B_TheUEXLOS:float
    C_TheUEXLOS:float
    D_TheUEXLOS:float
    A_TheFLOWOP:float
    B_TheFLOWOP:float
    C_TheFLOWOP:float
    D_TheFLOWOP:float
    A_TheTOTAL:float
    B_TheTOTAL:float
    C_TheTOTAL:float
    D_TheTOTAL:float
    Diff_OLCT:float
    Diff_SDGG:float
    Diff_AO:float
    Diff_OIC:float
    Diff_OIWFA:float
    Diff_PMI:float
    Diff_D:float
    Diff_WW:float
    Diff_UEXLOS:float
    Diff_FLOWOP:float
    Diff_TOTAL:float